################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
sqlite/tea/generic \
sqlite \
sqlite/.libs \
picnic \
. \
jsoncpp/src/test_lib_json \
jsoncpp/src/lib_json \
jsoncpp/src/jsontestrunner \
jsoncpp/buildscons/linux-gcc-4.2.1/src/test_lib_json \
jsoncpp/buildscons/linux-gcc-4.2.1/src/lib_json \
jsoncpp/buildscons/linux-gcc-4.2.1/src/jsontestrunner \
Swiftob \
Swiften/VCards \
Swiften/VCards/UnitTest \
Swiften/TLS/UnitTest \
Swiften/TLS \
Swiften/TLS/OpenSSL \
Swiften/StringCodecs/UnitTest \
Swiften/StringCodecs \
Swiften/StreamStack \
Swiften/StreamStack/UnitTest \
Swiften/StreamManagement/UnitTest \
Swiften/StreamManagement \
Swiften/Session \
Swiften/Server \
Swiften/Server/UnitTest \
Swiften/Serializer \
Swiften/Serializer/XML \
Swiften/Serializer/XML/UnitTest \
Swiften/Serializer/UnitTest \
Swiften/Serializer/PayloadSerializers \
Swiften/Serializer/PayloadSerializers/UnitTest \
Swiften/SASL/UnitTest \
Swiften/SASL \
Swiften/Roster \
Swiften/Roster/UnitTest \
Swiften/Queries/UnitTest \
Swiften/Queries/Responders \
Swiften/Queries/Requests/UnitTest \
Swiften/Queries/Requests \
Swiften/Queries \
Swiften/QA/TLSTest \
Swiften/QA/StorageTest \
Swiften/QA/ReconnectTest \
Swiften/QA/NetworkTest \
Swiften/QA/DNSSDTest \
Swiften/QA/ClientTest \
Swiften/Presence/UnitTest \
Swiften/Presence \
Swiften/Parser \
Swiften/Parser/UnitTest \
Swiften/Parser/PayloadParsers \
Swiften/Parser/PayloadParsers/UnitTest \
Swiften/Network/UnitTest \
Swiften/Network \
Swiften/MUC/UnitTest \
Swiften/MUC \
Swiften/LinkLocal/UnitTest \
Swiften/LinkLocal \
Swiften/LinkLocal/DNSSD \
Swiften/LinkLocal/DNSSD/Fake \
Swiften/LinkLocal/DNSSD/Bonjour \
Swiften/LinkLocal/DNSSD/Avahi \
Swiften/Jingle \
Swiften/JID/UnitTest \
Swiften/JID \
Swiften/IDN \
Swiften/History/UnitTest \
Swiften/History \
Swiften/FileTransfer \
Swiften/FileTransfer/UnitTest \
Swiften/Examples/SendMessage \
Swiften/Examples/SendFile \
Swiften/Examples/ParserTester \
Swiften/Examples/LinkLocalTool \
Swiften/Examples/ConnectivityTest \
Swiften/Examples/BenchTool \
Swiften/EventLoop/UnitTest \
Swiften/EventLoop \
Swiften/EventLoop/Cocoa \
Swiften/Entity \
Swiften/Elements \
Swiften/Elements/UnitTest \
Swiften/Disco/UnitTest \
Swiften/Disco \
Swiften/Config \
Swiften/Compress \
Swiften/Compress/UnitTest \
Swiften/Component/UnitTest \
Swiften/Component \
Swiften/Client/UnitTest \
Swiften/Client \
Swiften/Chat/UnitTest \
Swiften/Chat \
Swiften/Base \
Swiften/Base/UnitTest \
Swiften/Avatars \
Swiften/Avatars/UnitTest \
Swift/QtUI \
Swift/QtUI/UserSearch \
Swift/QtUI/Roster \
Swift/QtUI/NotifierTest \
Swift/QtUI/MUCSearch \
Swift/QtUI/EventViewer \
Swift/QtUI/ChatView \
Swift/QtUI/ChatList \
Swift/QtUI/ApplicationTest \
Swift/Controllers/XMPPEvents \
Swift/Controllers \
Swift/Controllers/UnitTest \
Swift/Controllers/UIInterfaces \
Swift/Controllers/UIEvents \
Swift/Controllers/Roster/UnitTest \
Swift/Controllers/Roster \
Swift/Controllers/Chat \
Swift/Controllers/Chat/UnitTest \
SwifTools/UnitTest \
SwifTools \
SwifTools/Notifier \
SwifTools/Idle \
SwifTools/Idle/UnitTest \
SwifTools/Idle/IdleQuerierTest \
SwifTools/Dock \
SwifTools/AutoUpdater \
SwifTools/Application \
SwifTools/Application/UnitTest \
Sluift \
Sluift/Lua \
Slimber \
Slimber/UnitTest \
Slimber/Qt \
Slimber/CLI \
QA/UnitTest/template \
QA/Checker \
Limber \
Documentation/SwiftenDevelopersGuide/Examples/EchoBot \
3rdParty/ZLib/src \
3rdParty/Snarl \
3rdParty/SQLite \
3rdParty/Lua/src \
3rdParty/LibIDN/src \
3rdParty/Expat/src \
3rdParty/CppUnit/src/src/cppunit \
3rdParty/CAres/src \
3rdParty/Boost \
3rdParty/Boost/src/tools/bcp \
3rdParty/Boost/src/libs/thread/src/win32 \
3rdParty/Boost/src/libs/thread/src \
3rdParty/Boost/src/libs/thread/src/pthread \
3rdParty/Boost/src/libs/system/src \
3rdParty/Boost/src/libs/signals/src \
3rdParty/Boost/src/libs/regex/src \
3rdParty/Boost/src/libs/program_options/src \
3rdParty/Boost/src/libs/filesystem/v3/src \
3rdParty/Boost/src/libs/filesystem/v2/src \
3rdParty/Boost/src/libs/detail \
3rdParty/Boost/src/libs/date_time/src/posix_time \
3rdParty/Boost/src/libs/date_time/src/gregorian \
.metadata/.plugins/org.eclipse.cdt.make.core \

